from __future__ import annotations

from datetime import date
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class AuthRepository(Protocol):
    reset_tokens: dict[str, str]

    def create_user(self, email: str, password_hash: str, display_name: str | None) -> Any: ...

    def get_user_by_email(self, email: str) -> Any | None: ...

    def get_user_by_id(self, user_id: str) -> Any | None: ...

    def update_password(self, email: str, password_hash: str) -> bool: ...


@runtime_checkable
class ProfileRepository(Protocol):
    def get(self, user_id: str) -> Any | None: ...

    def upsert(self, user_id: str, data: dict[str, Any]) -> Any: ...


@runtime_checkable
class SubscriptionRepository(Protocol):
    def get(self, user_id: str) -> Any: ...

    def save(self, subscription: Any) -> Any: ...


@runtime_checkable
class UsageCounterRepository(Protocol):
    def get_or_create(self, user_id: str, target_date: date) -> Any: ...

    def increment(self, user_id: str, target_date: date, purpose: str, amount: int = 1) -> Any: ...


@runtime_checkable
class ChatRepository(Protocol):
    def create_thread(self, user_id: str, title: str, kind: str) -> Any: ...

    def list_threads(self, user_id: str) -> list[Any]: ...

    def get_thread(self, user_id: str, thread_id: str) -> Any | None: ...

    def add_message(self, message: Any) -> Any: ...

    def list_messages(self, thread_id: str) -> list[Any]: ...


@runtime_checkable
class FoodLogRepository(Protocol):
    def create(self, log: Any) -> Any: ...

    def get_for_user(self, user_id: str, food_log_id: str) -> Any | None: ...

    def list_for_user(self, user_id: str, target_date: date | None = None) -> list[Any]: ...

    def save(self, log: Any) -> Any: ...

    def delete(self, user_id: str, food_log_id: str) -> bool: ...


@runtime_checkable
class WorkoutLogRepository(Protocol):
    def create(self, log: Any) -> Any: ...

    def get_for_user(self, user_id: str, workout_log_id: str) -> Any | None: ...

    def list_for_user(self, user_id: str, target_date: date | None = None) -> list[Any]: ...

    def save(self, log: Any) -> Any: ...


@runtime_checkable
class CheckinRepository(Protocol):
    def create(self, checkin: Any) -> Any: ...

    def get_for_user(self, user_id: str, checkin_id: str) -> Any | None: ...

    def list_for_user(self, user_id: str, target_date: date | None = None) -> list[Any]: ...

    def save(self, checkin: Any) -> Any: ...

    def delete(self, user_id: str, checkin_id: str) -> bool: ...


@runtime_checkable
class SafetyEventRepository(Protocol):
    def create(self, event: Any) -> Any: ...

    def list_events(self) -> list[Any]: ...


@runtime_checkable
class ModelCallRepository(Protocol):
    def create(self, call: Any) -> Any: ...

    def list_recent(self, limit: int = 100) -> list[Any]: ...

    def metrics(self) -> dict[str, Any]: ...
