import { StyleSheet } from 'react-native';
import { colors, compactPhone, narrowPhone, roomyPhone, size, topSafe } from './theme';

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  sheet: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    backgroundColor: colors.bg,
  },
  auth: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  authScroll: {
    flexGrow: 1,
    paddingHorizontal: narrowPhone ? 16 : 18,
    paddingTop: topSafe + (compactPhone ? 14 : 18),
    paddingBottom: compactPhone ? 16 : 22,
  },
  authHero: {
    marginTop: roomyPhone ? 52 : 32,
    marginBottom: compactPhone ? 20 : 24,
  },
  authTitle: {
    marginTop: compactPhone ? 22 : 30,
    marginBottom: compactPhone ? 18 : 24,
  },
  authFooter: {
    paddingTop: compactPhone ? 18 : 28,
  },
  heroTitle: {
    color: colors.text,
    fontSize: narrowPhone ? 27 : 29,
    lineHeight: narrowPhone ? 32 : 34,
    fontWeight: '900',
    marginBottom: 10,
  },
  heroSub: {
    color: colors.muted,
    fontSize: size(13),
  },
  flex: {
    flex: 1,
  },
  chatHeader: {
    minHeight: compactPhone ? 58 : 64,
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingTop: 8,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  menuButton: {
    width: compactPhone ? 38 : 40,
    height: compactPhone ? 38 : 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  menuLine: {
    width: 22,
    height: 3,
    borderRadius: 999,
    backgroundColor: colors.text,
  },
  subscribeButton: {
    minWidth: compactPhone ? 44 : 48,
    height: compactPhone ? 34 : 36,
    borderRadius: 999,
    backgroundColor: colors.lime,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  subscribeText: {
    color: '#111',
    fontWeight: '900',
    fontSize: size(12),
  },
  headerAvatar: {
    width: compactPhone ? 34 : 36,
    height: compactPhone ? 34 : 36,
    borderRadius: 999,
    backgroundColor: '#34332e',
    borderWidth: 1,
    borderColor: 'rgba(200,255,61,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAvatarText: {
    color: colors.lime,
    fontWeight: '900',
    fontSize: size(13),
  },
  chatTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  chatTitle: {
    color: colors.text,
    fontSize: narrowPhone ? 16 : 17,
    fontWeight: '900',
  },
  chatSubtitle: {
    color: colors.muted,
    fontSize: narrowPhone ? 11 : 12,
    marginTop: 2,
  },
  topbar: {
    minHeight: topSafe + (compactPhone ? 64 : 70),
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingTop: topSafe + 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  compactTopbar: {
    minHeight: compactPhone ? 64 : 70,
    paddingTop: 10,
  },
  brandRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    minWidth: 0,
  },
  brandCopy: {
    flex: 1,
    minWidth: 0,
  },
  mark: {
    width: size(32),
    height: size(32),
    borderRadius: 9,
    backgroundColor: colors.lime,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markText: {
    color: '#101010',
    fontWeight: '900',
  },
  h1: {
    color: colors.text,
    fontSize: narrowPhone ? 17 : 18,
    fontWeight: '900',
  },
  h2: {
    color: colors.text,
    fontSize: narrowPhone ? 15 : 16,
    fontWeight: '900',
  },
  body: {
    color: colors.text,
    fontSize: size(14),
    lineHeight: size(20),
  },
  bodyStrong: {
    color: colors.text,
    fontSize: size(14),
    fontWeight: '800',
  },
  muted: {
    color: colors.muted,
    fontSize: size(12),
    lineHeight: size(18),
  },
  content: {
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingTop: 12,
    paddingBottom: compactPhone ? 18 : 24,
    gap: compactPhone ? 10 : 12,
  },
  keyboardContent: {
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingTop: 12,
    paddingBottom: compactPhone ? 130 : 150,
    gap: compactPhone ? 10 : 12,
  },
  field: {
    marginBottom: compactPhone ? 11 : 13,
    gap: 6,
  },
  compactField: {
    flexGrow: 1,
    flexBasis: narrowPhone ? '46%' : '22%',
    minWidth: 0,
    marginBottom: 0,
  },
  label: {
    color: colors.muted,
    fontSize: size(12),
  },
  input: {
    minHeight: compactPhone ? 44 : 47,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: '#242424',
    color: colors.text,
    paddingHorizontal: 14,
  },
  formStatus: {
    color: colors.lime,
    fontSize: size(12),
    lineHeight: size(18),
    fontWeight: '800',
    marginTop: 8,
  },
  warningText: {
    color: '#f5c542',
    fontSize: size(12),
    lineHeight: size(18),
    fontWeight: '800',
  },
  runtimeInfo: {
    color: colors.muted,
    fontSize: size(11),
    lineHeight: size(16),
    marginTop: 10,
  },
  runtimeBanner: {
    color: colors.muted,
    fontSize: size(10),
    lineHeight: size(14),
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingTop: 6,
  },
  button: {
    minHeight: compactPhone ? 44 : 47,
    borderRadius: 12,
    backgroundColor: colors.lime,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    flexShrink: 1,
    minWidth: 0,
  },
  secondaryButton: {
    backgroundColor: '#2b2b2b',
  },
  disabledButton: {
    opacity: 0.55,
  },
  buttonText: {
    color: '#111',
    fontWeight: '900',
  },
  secondaryButtonText: {
    color: colors.text,
  },
  linkRow: {
    marginTop: compactPhone ? 10 : 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  link: {
    color: colors.lime,
    fontSize: size(13),
    fontWeight: '800',
  },
  iconButton: {
    width: compactPhone ? 36 : 38,
    height: compactPhone ? 36 : 38,
    borderRadius: 11,
    backgroundColor: '#2a2a2a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconText: {
    color: colors.text,
    fontSize: size(18),
    fontWeight: '900',
  },
  quickRow: {
    flexDirection: 'row',
    gap: 7,
    flexWrap: 'nowrap',
  },
  smallButton: {
    flex: 1,
    minWidth: 0,
    minHeight: compactPhone ? 38 : 40,
    borderRadius: 12,
    backgroundColor: '#2b2b2b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallButtonText: {
    color: colors.text,
    fontSize: narrowPhone ? 11 : size(12),
    fontWeight: '900',
  },
  bubble: {
    maxWidth: narrowPhone ? '92%' : '88%',
    borderRadius: 15,
    padding: compactPhone ? 11 : 12,
  },
  aiBubble: {
    alignSelf: 'flex-start',
    backgroundColor: colors.panel,
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: '#3a382f',
  },
  chatImageFrame: {
    gap: 6,
    marginBottom: 8,
  },
  chatImage: {
    width: narrowPhone ? 190 : 220,
    height: narrowPhone ? 142 : 164,
    borderRadius: 10,
    backgroundColor: '#202020',
  },
  chatImageCaption: {
    color: colors.muted,
    fontSize: size(11),
    fontWeight: '700',
  },
  card: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: colors.panel,
    borderRadius: 8,
    padding: compactPhone ? 12 : 14,
    gap: compactPhone ? 10 : 12,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
    flexWrap: 'wrap',
  },
  metricGrid: {
    flexDirection: 'row',
    gap: 7,
    flexWrap: 'nowrap',
  },
  metric: {
    flex: 1,
    minWidth: 0,
    backgroundColor: '#191919',
    borderRadius: 8,
    padding: compactPhone ? 8 : 10,
  },
  metricValue: {
    color: colors.text,
    fontWeight: '900',
    fontSize: narrowPhone ? 13 : 14,
  },
  metricLabel: {
    color: colors.muted,
    fontSize: size(11),
    marginTop: 2,
  },
  fileInsightCard: {
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(200,255,61,0.28)',
    backgroundColor: '#24241f',
    padding: compactPhone ? 10 : 12,
    gap: 9,
  },
  fileInsightTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  fileInsightGrid: {
    flexDirection: 'row',
    gap: 7,
    flexWrap: 'wrap',
  },
  fileInsightMetric: {
    flexGrow: 1,
    flexBasis: narrowPhone ? '46%' : '22%',
    minWidth: 0,
    backgroundColor: '#191919',
    borderRadius: 8,
    padding: compactPhone ? 8 : 10,
  },
  status: {
    color: colors.amber,
    fontSize: size(12),
    fontWeight: '900',
  },
  doneStatus: {
    color: colors.green,
  },
  twoCol: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  formGrid: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  actionGrid: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  actionButton: {
    flex: 1,
    minWidth: narrowPhone ? '46%' : 0,
  },
  portionEditor: {
    gap: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(200,255,61,0.28)',
    backgroundColor: '#24241f',
    padding: compactPhone ? 10 : 12,
  },
  portionInput: {
    minHeight: compactPhone ? 76 : 88,
    textAlignVertical: 'top',
    borderColor: 'rgba(200,255,61,0.46)',
    color: colors.text,
  },
  detailInput: {
    minHeight: compactPhone ? 108 : 132,
    paddingTop: 12,
    textAlignVertical: 'top',
    color: colors.text,
  },
  editorHeader: {
    minHeight: compactPhone ? 64 : 72,
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingTop: topSafe + 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  editorContent: {
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingTop: 14,
    paddingBottom: compactPhone ? 18 : 24,
    gap: compactPhone ? 10 : 12,
  },
  editorFooter: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingTop: 8,
    paddingBottom: compactPhone ? 12 : 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  composer: {
    gap: 8,
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingVertical: compactPhone ? 9 : 11,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  composerControls: {
    flexDirection: 'row',
    gap: 7,
    alignItems: 'center',
  },
  pendingAttachment: {
    alignSelf: 'flex-start',
    maxWidth: '82%',
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: '#242424',
    padding: 10,
  },
  pendingAttachmentBadge: {
    width: 48,
    height: 52,
    borderRadius: 8,
    backgroundColor: '#f7f7f2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingAttachmentType: {
    color: '#555',
    fontSize: size(12),
    fontWeight: '900',
  },
  pendingAttachmentMeta: {
    flexShrink: 1,
    gap: 3,
  },
  pendingAttachmentName: {
    color: colors.text,
    fontSize: size(14),
    lineHeight: size(18),
    fontWeight: '800',
  },
  pendingAttachmentSize: {
    color: colors.muted,
    fontSize: size(11),
    fontWeight: '700',
  },
  pendingAttachmentRemove: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#111',
    alignItems: 'center',
    justifyContent: 'center',
  },
  composerInput: {
    flex: 1,
    minHeight: compactPhone ? 38 : 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: '#242424',
    color: colors.muted,
    paddingHorizontal: 12,
  },
  tabs: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingTop: compactPhone ? 8 : 10,
    paddingBottom: compactPhone ? 10 : 13,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  tab: {
    flex: 1,
    minHeight: compactPhone ? 42 : 46,
    borderRadius: 14,
    backgroundColor: '#282828',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTab: {
    backgroundColor: colors.lime,
  },
  tabText: {
    color: colors.muted,
    fontWeight: '900',
  },
  activeTabText: {
    color: '#111',
  },
  summaryBand: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: '#24241f',
    padding: compactPhone ? 12 : 14,
    gap: compactPhone ? 10 : 12,
  },
  score: {
    color: colors.lime,
    fontSize: narrowPhone ? 20 : 22,
    fontWeight: '900',
  },
  recordCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: colors.panel,
    padding: compactPhone ? 10 : 12,
    gap: 7,
  },
  recordActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  planCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: colors.panel,
    padding: compactPhone ? 12 : 14,
    gap: 8,
    marginBottom: 8,
  },
  featuredPlan: {
    borderColor: 'rgba(200,255,61,0.62)',
    backgroundColor: '#25271e',
  },
  selectedPlan: {
    borderColor: colors.lime,
  },
  price: {
    color: colors.text,
    fontSize: narrowPhone ? 22 : 24,
    fontWeight: '900',
  },
  settingsRow: {
    minHeight: compactPhone ? 50 : 56,
    borderRadius: 8,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsProfile: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: colors.panel,
    padding: 16,
    alignItems: 'center',
    gap: 8,
  },
  sectionLabel: {
    color: colors.muted,
    fontSize: size(13),
    fontWeight: '800',
    marginTop: 12,
    marginLeft: 4,
  },
  settingsIcon: {
    width: 24,
    color: colors.text,
    fontSize: size(17),
    fontWeight: '900',
    textAlign: 'center',
  },
  settingsValue: {
    flex: 1,
    color: colors.muted,
    fontSize: size(13),
    fontWeight: '800',
    textAlign: 'right',
  },
  privacyCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(200,255,61,0.28)',
    backgroundColor: '#24241f',
    padding: compactPhone ? 12 : 14,
    gap: 8,
  },
  profileCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: colors.panel,
    padding: compactPhone ? 12 : 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: compactPhone ? 42 : 46,
    height: compactPhone ? 42 : 46,
    borderRadius: 999,
    backgroundColor: colors.lime,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#111',
    fontWeight: '900',
    fontSize: size(14),
  },
  profileCopy: {
    flex: 1,
    minWidth: 0,
  },
  menuRow: {
    minHeight: compactPhone ? 50 : 54,
    borderRadius: 8,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  dangerText: {
    color: colors.danger,
    fontWeight: '800',
  },
  panelOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    justifyContent: 'flex-end',
  },
  drawerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
    flexDirection: 'row',
  },
  drawerScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.42)',
  },
  threadDrawer: {
    width: narrowPhone ? '84%' : '78%',
    maxWidth: 360,
    backgroundColor: '#1d1d1b',
    borderRightWidth: 1,
    borderRightColor: 'rgba(255,255,255,0.1)',
    paddingTop: topSafe + 10,
    paddingHorizontal: 14,
    paddingBottom: 18,
    gap: 10,
  },
  drawerFlex: {
    flex: 1,
  },
  drawerHeader: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  userMenuCard: {
    minHeight: 66,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(200,255,61,0.28)',
    backgroundColor: '#24241f',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  threadRow: {
    minHeight: 58,
    borderRadius: 8,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  drawerNewChat: {
    alignSelf: 'flex-end',
    minHeight: 58,
    borderRadius: 999,
    backgroundColor: '#050505',
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  drawerNewIcon: {
    color: colors.text,
    fontSize: 23,
    fontWeight: '900',
  },
  drawerNewText: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '900',
  },
  panelScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.42)',
  },
  bottomPanel: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: '#1d1d1b',
    paddingHorizontal: narrowPhone ? 12 : 14,
    paddingTop: 8,
    paddingBottom: compactPhone ? 14 : 18,
    gap: 12,
  },
  panelHandle: {
    alignSelf: 'center',
    width: 38,
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.26)',
    marginBottom: 4,
  },
  miniClose: {
    width: 32,
    height: 32,
    borderRadius: 999,
    backgroundColor: '#2a2a2a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  panelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  panelAction: {
    flexGrow: 1,
    flexBasis: narrowPhone ? '46%' : '30%',
    minHeight: compactPhone ? 72 : 78,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: colors.panel,
    padding: 10,
    justifyContent: 'center',
  },
  pill: {
    alignSelf: 'flex-start',
    minHeight: compactPhone ? 24 : 26,
    paddingHorizontal: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(200,255,61,0.14)',
    justifyContent: 'center',
  },
  pillText: {
    color: colors.lime,
    fontSize: size(12),
    fontWeight: '900',
  },
});
